name: go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build and package binaries
      run: |
        for arch in arm amd64; do
          mkdir -p build/$arch
          env GOOS=linux GOARCH=$arch go build -o build/$arch/goshoutbox cmd/goshoutbox/goshoutbox.go 
          cp -r web build/$arch/
          cp minimal-config.json build/$arch/config.json
        done

    - name: Archive arm build
      uses: actions/upload-artifact@v2
      with:
        name: goshoutbox-arm
        path: build/arm

    - name: Archive amd64 build
      uses: actions/upload-artifact@v2
      with:
        name: goshoutbox-amd
        path: build/amd64

