name: go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build and package binaries
      run: |
        mkdir artifacts
        for arch in arm amd64; do
          mkdir -p build/$arch
          env GOOS=linux GOARCH=$arch go build -o build/$arch/goshoutbox cmd/goshoutbox/goshoutbox.go 
          cp -r web build/$arch/
          cp minimal-config.json build/$arch/config.json
          cd build/$arch
          tar cvf ../../artifacts/goshoutbox-$arch.tar.gz .
          cd ../../
        done

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: goshoutbox
        path: |
          artifacts/goshoutbox-arm.tar.gz
          artifacts/goshoutbox-amd64.tar.gz

      

